// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConditionFilter: typeof import('./components/ConditionFilter/index.vue')['default']
    FilterInput: typeof import('./components/ConditionFilter/FilterInput.vue')['default']
    FilterSelect: typeof import('./components/ConditionFilter/FilterSelect.vue')['default']
    FilterTime: typeof import('./components/ConditionFilter/FilterTime.vue')['default']
    FilterTimeRange: typeof import('./components/ConditionFilter/FilterTimeRange.vue')['default']
    LayoutBreadcrumb: typeof import('./components/LayoutBreadcrumb.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutUser: typeof import('./components/LayoutUser.vue')['default']
    LeftMenu: typeof import('./components/LeftMenu.vue')['default']
    MModal: typeof import('./components/MModal.vue')['default']
    PageMain: typeof import('./components/PageMain.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePage: typeof import('./components/TablePage.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
