/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConditionFilter: typeof import('./components/ConditionFilter/index.vue')['default']
    FilterSelect: typeof import('./components/ConditionFilter/FilterSelect.vue')['default']
    FilterTime: typeof import('./components/ConditionFilter/FilterTime.vue')['default']
    FilterTimeRange: typeof import('./components/ConditionFilter/FilterTimeRange.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LayoutBreadcrumb: typeof import('./components/LayoutBreadcrumb.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutUser: typeof import('./components/LayoutUser.vue')['default']
    LeftMenu: typeof import('./components/LeftMenu.vue')['default']
    MModal: typeof import('./components/MModal.vue')['default']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NMenu: typeof import('naive-ui')['NMenu']
    PageMain: typeof import('./components/PageMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePage: typeof import('./components/TablePage.vue')['default']
  }
}
